language: java
jdk:
- oraclejdk7
sudo: false
install: true
script: "./buildViaTravis.sh"
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
before_install:
- test $TRAVIS_PULL_REQUEST = false && openssl aes-256-cbc -K $encrypted_5d5868ca2cc9_key -iv $encrypted_5d5868ca2cc9_iv -in gradle.properties.enc -out gradle.properties -d || true